#!/bin/bash
echo Creating pleiades+
echo -------------

echo downloading Pleiades files
for i in locations names places; do
  wget http://atlantides.org/downloads/pleiades/dumps/pleiades-${i}-latest.csv.gz -nc 
  gunzip -fk pleiades-${i}-latest.csv.gz
done

echo download geonames files
mkdir /tmp/geonames
for i in AL BA CY DZ EG ES FR GR HR IL IT LB LY MA MT PT TN TR SY JO GB CH MK SI HU DE LI SM VA LU AD BE NL AT YE RS DK IE RO BG IR AM XK IQ GI AE SA AF OM KW ET IN LK PK PS RU BH UA GG SD GE AZ no-country; do
  wget http://download.geonames.org/export/dump/${i}.zip -nc -O /tmp/geonames/${i}.zip
done
# wget http://download.geonames.org/export/dump/AL.zip -nc -O /tmp/geonames/AL.zip #Albania
# wget http://download.geonames.org/export/dump/BA.zip -nc -O /tmp/geonames/BA.zip #Bosnia
# wget http://download.geonames.org/export/dump/CY.zip -nc -O /tmp/geonames/CY.zip #Cyprus
# wget http://download.geonames.org/export/dump/DZ.zip -nc -O /tmp/geonames/DZ.zip #Algeria
# wget http://download.geonames.org/export/dump/EG.zip -nc -O /tmp/geonames/EG.zip #Egypt
# wget http://download.geonames.org/export/dump/ES.zip -nc -O /tmp/geonames/ES.zip #Spain
# wget http://download.geonames.org/export/dump/FR.zip -nc -O /tmp/geonames/FR.zip #France
# wget http://download.geonames.org/export/dump/GR.zip -nc -O /tmp/geonames/GR.zip #Greece
# wget http://download.geonames.org/export/dump/HR.zip -nc -O /tmp/geonames/HR.zip #Croatia
# wget http://download.geonames.org/export/dump/IL.zip -nc -O /tmp/geonames/IL.zip #Israel
# wget http://download.geonames.org/export/dump/IT.zip -nc -O /tmp/geonames/IT.zip #Italy
# wget http://download.geonames.org/export/dump/LB.zip -nc -O /tmp/geonames/LB.zip #Lebanon
# wget http://download.geonames.org/export/dump/LY.zip -nc -O /tmp/geonames/LY.zip #Libya
# wget http://download.geonames.org/export/dump/MA.zip -nc -O /tmp/geonames/MA.zip #Morocco
# wget http://download.geonames.org/export/dump/MT.zip -nc -O /tmp/geonames/MT.zip #Malta
# wget http://download.geonames.org/export/dump/PT.zip -nc -O /tmp/geonames/PT.zip #Portugal
# wget http://download.geonames.org/export/dump/TN.zip -nc -O /tmp/geonames/TN.zip #Tunisia
# wget http://download.geonames.org/export/dump/TR.zip -nc -O /tmp/geonames/TR.zip #Turkey
# wget http://download.geonames.org/export/dump/SY.zip -nc -O /tmp/geonames/SY.zip #Syria?
# wget http://download.geonames.org/export/dump/JO.zip -nc -O /tmp/geonames/JO.zip #Jordan?
# wget http://download.geonames.org/export/dump/GB.zip -nc -O /tmp/geonames/GB.zip #Britain?
# wget http://download.geonames.org/export/dump/CH.zip -nc -O /tmp/geonames/CH.zip #Switzerland?
# wget http://download.geonames.org/export/dump/GB.zip -nc -O /tmp/geonames/GB.zip #Britain
# wget http://download.geonames.org/export/dump/MK.zip -nc -O /tmp/geonames/MK.zip #Macedonia
#SI Slovenia
#HU Hungary
#DE Germany
#LI Lichtenstein
#SM San Marino
#VA Vatican
#LU Luxembourg
#AD Andorra
#BE Belgium
#NL Netherlands

echo unzip geonames
for i in /tmp/geonames/*.zip; do
  unzip -o $i -d /tmp/geonames
done

rm -v /tmp/geonames/readme.txt

cat /tmp/geonames/*.txt > all-geonames.txt

./pleiades-plus.rb pleiades-places-latest.csv pleiades-names-latest.csv pleiades-locations-latest.csv all-geonames.txt | sort | uniq > pleiades-plus.csv





